
////
     Licensed to the Apache Software Foundation (ASF) under one
     or more contributor license agreements.  See the NOTICE file
     distributed with this work for additional information
     regarding copyright ownership.  The ASF licenses this file
     to you under the Apache License, Version 2.0 (the
     "License"); you may not use this file except in compliance
     with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing,
     software distributed under the License is distributed on an
     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
     KIND, either express or implied.  See the License for the
     specific language governing permissions and limitations
     under the License.
////
= Apache NetBeans source and daily builds
:page-layout: page
:page-tags: 
:jbake-status: published
:keywords: Apache NetBeans source and daily builds
:icons: font
:description: Apache NetBeans source and daily builds

All Apache NetBeans source code is freely available to build yourself, or you can
download (unsupported) daily development builds.

== Daily builds

Please visit link:https://ci-builds.apache.org/job/Netbeans/job/netbeans-linux/[https://ci-builds.apache.org/job/Netbeans/job/netbeans-linux/] for the daily builds.

== Building from source

You can of course build Apache NetBeans from source. 

For more information goto: link:https://cwiki.apache.org/confluence/display/NETBEANS/Development+Environment[https://cwiki.apache.org/confluence/display/NETBEANS/Development+Environment]

After you have built Apache NetBeans from source you may want to xref:participate/submit-pr.adoc[submit a pull request].

=== Repositories

This is a list of Apache NetBeans repositories:

- link:https://github.com/apache/netbeans[https://github.com/apache/netbeans] The main source code repository.
- link:https://github.com/apache/netbeans-l10n[https://github.com/apache/netbeans-l10n] Translation bundle repository.
- link:https://github.com/apache/netbeans-website[https://github.com/apache/netbeans-website] This website's repository.
- link:https://github.com/apache/netbeans-website-cleanup[https://github.com/apache/netbeans-website-cleanup] A repository used to clean up existing documentation from pass:[http://netbeans.org]
- link:https://github.com/apache/netbeans-tools[https://github.com/apache/netbeans-tools] Tools and facilities in support of the Apache NetBeans project.
- Emilian Bold has converted the previous Mercurial repository (pass:[http://hg.netbeans.org]) to git, for historical reference, and has kindly uploaded it to GitHub at https://github.com/emilianbold/netbeans-releases. Thanks, Emilian!

